steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Run py script: hello world
  - name: python
    entrypoint: python
    args: ["hello_world.py"] 

  # Run py script: list files
  - name: python
    entrypoint: python
    args: ["list_files.py"] 
    
  # Run py script: raise error manually
  - name: python
    entrypoint: python
    args: ["raise_error.py"] 