steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  - name: python
    entrypoint: python
    args: ["summarize_pr.py"]
    env: 
      - 'GITHUB_TOKEN=$_GITHUB_TOKEN'
      - 'REPO_FULL_NAME=$REPO_FULL_NAME'
      - 'REPO_NAME=$REPO_NAME'
      - 'PR_NUMBER=$_PR_NUMBER'
      - 'MODEL_ID=$_MODEL_ID'
