steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Run py script: hello world
  - name: python
    entrypoint: python
    args: ["hello_world.py", "12", "${_SECRET_NUMBER}"]

  # Run py script: hello Gemini
  - name: python
    entrypoint: python
    args: ["hello_gemini.py"]


  # Run py script: list files
  - name: python
    entrypoint: python
    args: ["list_files.py"]
    
  - name: python
    entrypoint: python
    args: ["summarize_pr.py"]
    env: 
      - 'GITHUB_TOKEN=$_GITHUB_TOKEN'
      - 'REPO_FULL_NAME=$REPO_FULL_NAME'
      - 'REPO_NAME=$REPO_NAME'
      - 'PULL_REQUEST_NUMBER=$$_PR_NUMBER'
      - 'MODEL_ID=$_MODEL_ID'
